spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logiweb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    mvc:
      view:
        prefix: /WEB-INF/view/
        suffix: .jsp